version: "3.8"

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: turborepo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/db/data

volumes:
  postgres_data:
